version: "3.5"

services:
  dev:
    build: "./"
    working_dir: "/app/"
    command: ["sleep", "infinity"]
    volumes:
      - "./:/app/:delegated"
    ports:
      - "${APP_PORT}:80"

  check:
    build: "./"
    working_dir: "/app/"
    volumes:
      - "./:/app/:delegated"
    command: ["sh", "-c", "make init && make check"]

  db:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    #ports:
    #  - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
